topology:
  dut_num: 1
  VMs:
    ARISTA01T3:
      vlans:
        - 0
      vm_offset: 0
    ARISTA02LT2:
      vlans:
        - 1
      vm_offset: 1
  DUT:
    loopback:
      ipv4:
        - 10.1.0.1/32
      ipv6:
        - FC00:10::1/128

configuration_properties:
  common:
    podset_number: 400
    tor_number: 16
    tor_subnet_number: 8
    max_tor_subnet_number: 32
    tor_subnet_size: 128
    dut_asn: 65100
    dut_type: UpperSpineRouter
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF
  core:
    swrole: core
  leaf:
    swrole: leaf

configuration:
  ARISTA01T3:
    properties:
      - common
      - core
    bgp:
      asn: 65200
      peers:
        65100:
          - 10.0.0.0
          - FC00::1
    interfaces:
      Loopback0:
        ipv4: 100.1.0.1/32
        ipv6: 2064:100::1/128
      Ethernet1:
        ipv4: 10.0.0.1/31
        ipv6: FC00::2/126
    bp_interface:
      ipv4: 10.10.246.1/24
      ipv6: FC0A::2/64

  ARISTA02LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      peers:
        65100:
          - 10.0.0.2
          - FC00::5
    interfaces:
      Loopback0:
        ipv4: 100.1.0.2/32
        ipv6: 2064:100::2/128
      Ethernet1:
        ipv4: 10.0.0.3/31
        ipv6: FC00::6/126
    bp_interface:
      ipv4: 10.10.246.2/24
      ipv6: FC0A::4/64
