topology:
  dut_num: 1
  VMs:
    ARISTA01T3:
      vlans:
        - 0
      vm_offset: 0
    ARISTA02T3:
      vlans:
        - 1
      vm_offset: 1
    ARISTA03LT2:
      vlans:
        - 2
      vm_offset: 2
    ARISTA04LT2:
      vlans:
        - 3
      vm_offset: 3
    ARISTA05LT2:
      vlans:
        - 4
      vm_offset: 4
  DUT:
    loopback:
      ipv4:
        - 10.1.0.1/32
      ipv6:
        - FC00:10::1/128

configuration_properties:
  common:
    podset_number: 400
    tor_number: 16
    tor_subnet_number: 8
    max_tor_subnet_number: 32
    tor_subnet_size: 128
    dut_asn: 65100
    dut_type: UpperSpineRouter
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF
  core:
    swrole: core
  leaf:
    swrole: leaf

configuration:
  ARISTA01T3:
    properties:
      - common
      - core
    bgp:
      asn: 65200
      peers:
        65100:
          - 10.0.0.0
          - FC00::1
    interfaces:
      Loopback0:
        ipv4: 100.1.0.1/32
        ipv6: 2064:100::1/128
      Ethernet1:
        ipv4: 10.0.0.1/31
        ipv6: FC00::2/126
    bp_interface:
      ipv4: 10.10.246.1/24
      ipv6: FC0A::2/64

  ARISTA02T3:
    properties:
      - common
      - core
    bgp:
      asn: 65201
      peers:
        65100:
          - 10.0.0.2
          - FC00::5
    interfaces:
      Loopback0:
        ipv4: 100.1.0.2/32
        ipv6: 2064:100::2/128
      Ethernet1:
        ipv4: 10.0.0.3/31
        ipv6: FC00::6/126
    bp_interface:
      ipv4: 10.10.246.2/24
      ipv6: FC0A::4/64

  ARISTA03LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      peers:
        65100:
          - 10.0.0.4
          - FC00::9
    interfaces:
      Loopback0:
        ipv4: 100.1.0.3/32
        ipv6: 2064:100::3/128
      Ethernet1:
        ipv4: 10.0.0.5/31
        ipv6: FC00::A/126
    bp_interface:
      ipv4: 10.10.246.3/24
      ipv6: FC0A::6/64

  ARISTA04LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65301
      peers:
        65100:
          - 10.0.0.6
          - FC00::D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.4/32
        ipv6: 2064:100::4/128
      Ethernet1:
        ipv4: 10.0.0.7/31
        ipv6: FC00::E/126
    bp_interface:
      ipv4: 10.10.246.4/24
      ipv6: FC0A::8/64

  ARISTA05LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65302
      peers:
        65100:
          - 10.0.0.8
          - FC00::11
    interfaces:
      Loopback0:
        ipv4: 100.1.0.5/32
        ipv6: 2064:100::5/128
      Ethernet1:
        ipv4: 10.0.0.9/31
        ipv6: FC00::12/126
    bp_interface:
      ipv4: 10.10.246.5/24
      ipv6: FC0A::A/64
